### ISSUE TITLE
update README to include working WebGL example

### ISSUE THREAD

**Issue by gpolyn** [Leeft/three-sprite-texture-atlas-manager#3]
Cannot get my WebGL attempt working at [ jsfiddle.net/gpolyn/en8fvx60/32](http://jsfiddle.net/gpolyn/en8fvx60/32).

Please update README to include guidance on working example.

**Comment by Leeft** [comment]
Sorry that took so long, I've not been doing any programming (as a hobby anyway) for a while as I've been busy with other things. There's an example now though: https://jsfiddle.net/Shiari/jzwg8ngn/

I'll amend the README later, perhaps tonight.

**Comment by Leeft** [comment]
It's now included in the README, hope the example is of use to you. Closing this issue.

**Comment by gpolyn** [comment]
Thank you so much!
